### ISSUE TITLE
[Dev] Backend will not initiate

### ISSUE THREAD

**Issue by Nebrethar** [chaoss/augur#392]
**Describe the bug:**
I cannot start my backend on the dev branch. 
I get an error that I am not sure of.

**To Reproduce:**
1. Clone augur
2. Checkout dev
3. Go to augur root directory
4. Command "augur run"

**Expected behavior:**
I hoped backend augur would start like it normally does.

**Screenshots**
I included the full trace from the error.

**Desktop (please complete the following information):**
 - OS: Windows 10 with Linux ss
 - Browser: Chrome 77

**Additional context**
```
Traceback (most recent call last):
  File "/mnt/c/Clones/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/mnt/c/Clones/venv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedTable: relation "gh_worker_job" does not exist
LINE 2:                         SELECT since_id_str FROM gh_worker_j...
                                                         ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/c/Clones/venv/bin/augur", line 12, in <module>
    sys.exit(run())
  File "/mnt/c/Clones/venv/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/mnt/c/Clones/venv/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/mnt/c/Clones/venv/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/mnt/c/Clones/venv/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/mnt/c/Clones/venv/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/mnt/c/Clones/venv/lib/python3.6/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/mnt/c/Clones/venv/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/mnt/c/Clones/venv/lib/python3.6/site-packages/augur-0.9.8-py3.6.egg/augur/runtime.py", line 23, in decorator
    function(app, *args, **kwargs)
  File "/mnt/c/Clones/venv/lib/python3.6/site-packages/augur-0.9.8-py3.6.egg/augur/cli/run.py", line 54, in cli
    dbname=app.read_config('Database', 'database', 'AUGUR_DB_NAME', 'msr14')
  File "/mnt/c/Clones/venv/lib/python3.6/site-packages/augur-0.9.8-py3.6.egg/augur/housekeeper/housekeeper.py", line 39, in __init__
    self.__updatable = self.prep_jobs(jobs)
  File "/mnt/c/Clones/venv/lib/python3.6/site-packages/augur-0.9.8-py3.6.egg/augur/housekeeper/housekeeper.py", line 180, in prep_jobs
    job_df = pd.read_sql(repoIdSQL, self.helper_db, params={})
  File "/mnt/c/Clones/venv/lib/python3.6/site-packages/pandas/io/sql.py", line 436, in read_sql
    chunksize=chunksize,
  File "/mnt/c/Clones/venv/lib/python3.6/site-packages/pandas/io/sql.py", line 1218, in read_query
    result = self.execute(*args)
  File "/mnt/c/Clones/venv/lib/python3.6/site-packages/pandas/io/sql.py", line 1087, in execute
    return self.connectable.execute(*args, **kwargs)
  File "/mnt/c/Clones/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2169, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/mnt/c/Clones/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/mnt/c/Clones/venv/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/mnt/c/Clones/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1107, in _execute_clauseelement
    distilled_params,
  File "/mnt/c/Clones/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    e, statement, parameters, cursor, context
  File "/mnt/c/Clones/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/mnt/c/Clones/venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/mnt/c/Clones/venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "/mnt/c/Clones/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/mnt/c/Clones/venv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) relation "gh_worker_job" does not exist
LINE 2:                         SELECT since_id_str FROM gh_worker_j...
                                                         ^

[SQL:
                        SELECT since_id_str FROM gh_worker_job
                        WHERE job_model = 'issues'
                    ]
(Background on this error at: http://sqlalche.me/e/f405)
```

**Comment by ccarterlandis** [comment]
@Nebrethar I'm unable to recreate this error on the latest version of `dev`. What is the output of `git log -n 1 dev`?

**Comment by Nebrethar** [comment]
@ccarterlandis 
```
commit b4e9f8303ea2db721c041d1e5c8c74adcba0781c (HEAD -> dev, origin/dev)
Author: Carter Landis <ccarterlandis@gmail.com>
Date:   Mon Sep 23 15:42:16 2019 -0500

    Remove runtime/ from version control

    Due to another .gitignore change, the runtime/ folder
    was getting checked into version control by accident.
    This commit removes it from version control, and a previous
    change has already removed it from the .gitignore.

    Signed-off-by: Carter Landis <ccarterlandis@gmail.com>
```

**Comment by ccarterlandis** [comment]
I'm thinking it may be an older version of `augur` that's being run somehow, running `make clean` should remove all the built files. You also may have to do `python setup.py install` again, sorry I forgot to mention that

**Comment by Nebrethar** [comment]
I fixed it (in the `augur run` directory) with:
```
make clean; sudo pip3 install -e .; python setup.py install; augur run
```
This should be documented somewhere, probably in `installing-augur.md`. I will make a PR

**Comment by Nebrethar** [comment]
Also @ccarterlandis thanks for your help. I was stuck on this one,

**Comment by sgoggins** [comment]
usually `make install` takes care of things on the dev branch these days ...

**Comment by Nebrethar** [comment]
@sgoggins either way, I've been working on the new architecture since it was instantiated and I never knew how to update after a pull. However it's done, it should be documented and easy to find.

**Comment by manangoel99** [comment]
@ccarterlandis @sgoggins I'm facing the same issue. I tried the steps written above by @Nebrethar but it still throws the same error.
```
Traceback (most recent call last):
  File "/home/manan/.virtualenvs/augur/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    cursor, statement, parameters, context
  File "/home/manan/.virtualenvs/augur/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 588, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedTable: relation "worker_history" does not exist
LINE 2: ...SELECT max(history_id) AS history_id, status FROM worker_his...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/manan/.virtualenvs/augur/bin/augur", line 11, in <module>
    load_entry_point('augur==0.11.0', 'console_scripts', 'augur')()
  File "/home/manan/.virtualenvs/augur/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/manan/.virtualenvs/augur/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/manan/.virtualenvs/augur/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/manan/.virtualenvs/augur/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/manan/.virtualenvs/augur/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/manan/.virtualenvs/augur/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/manan/.virtualenvs/augur/lib/python3.7/site-packages/augur-0.11.0-py3.7.egg/augur/cli/run.py", line 119, in cli
    dbname=app.read_config('Database', 'name')
  File "/home/manan/.virtualenvs/augur/lib/python3.7/site-packages/augur-0.11.0-py3.7.egg/augur/housekeeper/housekeeper.py", line 47, in __init__
    self.__updatable = self.prep_jobs(jobs)
  File "/home/manan/.virtualenvs/augur/lib/python3.7/site-packages/augur-0.11.0-py3.7.egg/augur/housekeeper/housekeeper.py", line 313, in prep_jobs
    history_df = pd.read_sql(jobHistorySQL, self.helper_db, params={})
  File "/home/manan/.virtualenvs/augur/lib/python3.7/site-packages/pandas/io/sql.py", line 438, in read_sql
    chunksize=chunksize,
  File "/home/manan/.virtualenvs/augur/lib/python3.7/site-packages/pandas/io/sql.py", line 1218, in read_query
    result = self.execute(*args)
  File "/home/manan/.virtualenvs/augur/lib/python3.7/site-packages/pandas/io/sql.py", line 1087, in execute
    return self.connectable.execute(*args, **kwargs)
  File "/home/manan/.virtualenvs/augur/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2191, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/home/manan/.virtualenvs/augur/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 984, in execute
    return meth(self, multiparams, params)
  File "/home/manan/.virtualenvs/augur/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 293, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/manan/.virtualenvs/augur/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1103, in _execute_clauseelement
    distilled_params,
  File "/home/manan/.virtualenvs/augur/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1288, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/manan/.virtualenvs/augur/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1482, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/manan/.virtualenvs/augur/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/home/manan/.virtualenvs/augur/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    cursor, statement, parameters, context
  File "/home/manan/.virtualenvs/augur/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 588, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) relation "worker_history" does not exist
LINE 2: ...SELECT max(history_id) AS history_id, status FROM worker_his...
                                                             ^

[SQL: 
                        SELECT max(history_id) AS history_id, status FROM worker_history
                        GROUP BY status
                        LIMIT 1
                    ]
(Background on this error at: http://sqlalche.me/e/f405)

```
